name: Build & Publish to Docker Hub
on:
  workflow_call:
    secrets:
      docker_hub_username:
        required: true
      docker_hub_access_token:
        required: true
jobs:
  build_and_push:
    name: Build & Publish
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[no build]') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: docker-buildx

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_access_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            thelegionpreservationproject/spellwork:latest
